spring:
  application:
    name: dubbo-server

server:
  port: 51001

dubbo:
  # 注册中心配置
  registry:
    # 协议
    protocol: zookeeper
    # 地址
    address: 192.168.81.128:2181, 192.168.81.129:2181, 192.168.81.130:2181
    # 客户端
    client: curator
